### ISSUE TITLE
Connect to user accounts

### ISSUE THREAD

**Issue by ericafenyo** [ericafenyo/tasti#37]
### Story
**As a** user, **I want to** log into my account, **so that** I can manage my profile.

### Validation criteria
- [x] Can create an account
- [x] Can connect to an account with valid credentials
- [x] Can reset a password
